apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: LoadBalancer
  selector:
    app: api-gateway-server
  ports:
    - protocol: TCP
      port: 5424
      targetPort: 6000

