apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-server
  namespace: auth-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: authentication-server
  template:
    metadata:
      labels:
        app: authentication-server
    spec:
      containers:
        - name: authentication-container
          image: authentication-management-server
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            # - name: USER_SERVICE # 나중에 통신할 서버로 바꾸기
            #   value: "http://authentication-service.auth-server:6001" # 여기도 동일
          envFrom:
            - configMapRef:
                name: postgresql-config
            - secretRef:
                name: postgresql-secret
            - configMapRef:
                name: redis-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 10"]
          readinessProbe:
            httpGet:
              path: /healthcheck/ready
              port: 6001
            initialDelaySeconds: 10
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck/live
              port: 6001
            initialDelaySeconds: 10
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 7