apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: auth-server
  labels:
    app: authentication-server
    tier: backend
  annotations:
    description: "Authentication service for Flow of Essence"
spec:
  selector:
    app: authentication-server
  ports:
    - protocol: TCP
      port: 6001