global:
  scrape_interval: 1m
  scrape_timeout: 15s
  evaluation_interval: 2m

  external_labels:
    monitor: 'monitor'
  query_log_file: query_log_file.log

scrape_configs:
  - job_name: 'monitoring-item'
    metrics_path: '/actuator/prometheus'
    honor_labels: false
    honor_timestamps: false
    scheme: 'http'